#EL_Asy.R
source("https://raw.githubusercontent.com/cftang9/GOF-PQD/refs/heads/main/Methods/EL_Asy.R")
#EL_Fin.R
source("https://raw.githubusercontent.com/cftang9/GOF-PQD/refs/heads/main/Methods/EL_Fin.R")
#DS2004.R
source("https://raw.githubusercontent.com/cftang9/GOF-PQD/refs/heads/main/Methods/DS2004.R")
#S2005.R
source("https://raw.githubusercontent.com/cftang9/GOF-PQD/refs/heads/main/Methods/S2005.R")
#GS2010.R
source("https://raw.githubusercontent.com/cftang9/GOF-PQD/refs/heads/main/Methods/GS2010.R")
#GS2013.R
source("https://raw.githubusercontent.com/cftang9/GOF-PQD/refs/heads/main/Methods/GS2013.R")
#LW2014.R
source("https://raw.githubusercontent.com/cftang9/GOF-PQD/refs/heads/main/Methods/LW2014.R")
#copula.est.ws.R
source("https://raw.githubusercontent.com/cftang9/GOF-PQD/refs/heads/main/Methods/copula.est.ws.R")
#copula.test.AD.R
source("https://raw.githubusercontent.com/cftang9/GOF-PQD/refs/heads/main/Methods/copula.test.AD.R")
