# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

DS <- function(x) {
    .Call(`_PQDtests_DS`, x)
}

GofPqd_Dist <- function(X) {
    .Call(`_PQDtests_GofPqd_Dist`, X)
}

GofPqd_el_prod <- function(X) {
    .Call(`_PQDtests_GofPqd_el_prod`, X)
}

GofPqd_el_joint <- function(X) {
    .Call(`_PQDtests_GofPqd_el_joint`, X)
}

IndPqd_Dist <- function(X) {
    .Call(`_PQDtests_IndPqd_Dist`, X)
}

IndPqd_el_prod <- function(X) {
    .Call(`_PQDtests_IndPqd_el_prod`, X)
}

IndPqd_el_joint <- function(X) {
    .Call(`_PQDtests_IndPqd_el_joint`, X)
}

timesTwo <- function(x) {
    .Call(`_PQDtests_timesTwo`, x)
}

timesTwo2 <- function(x) {
    .Call(`_PQDtests_timesTwo2`, x)
}

rcpp_hello_world <- function() {
    .Call(`_PQDtests_rcpp_hello_world`)
}

