// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// DS
double DS(NumericVector x);
RcppExport SEXP _PQDtests_DS(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(DS(x));
    return rcpp_result_gen;
END_RCPP
}
// GofPqd_Dist
Rcpp::List GofPqd_Dist(NumericMatrix X);
RcppExport SEXP _PQDtests_GofPqd_Dist(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(GofPqd_Dist(X));
    return rcpp_result_gen;
END_RCPP
}
// GofPqd_el_prod
double GofPqd_el_prod(NumericMatrix X);
RcppExport SEXP _PQDtests_GofPqd_el_prod(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(GofPqd_el_prod(X));
    return rcpp_result_gen;
END_RCPP
}
// GofPqd_el_joint
double GofPqd_el_joint(NumericMatrix X);
RcppExport SEXP _PQDtests_GofPqd_el_joint(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(GofPqd_el_joint(X));
    return rcpp_result_gen;
END_RCPP
}
// IndPqd_Dist
Rcpp::List IndPqd_Dist(NumericMatrix X);
RcppExport SEXP _PQDtests_IndPqd_Dist(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(IndPqd_Dist(X));
    return rcpp_result_gen;
END_RCPP
}
// IndPqd_el_prod
double IndPqd_el_prod(NumericMatrix X);
RcppExport SEXP _PQDtests_IndPqd_el_prod(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(IndPqd_el_prod(X));
    return rcpp_result_gen;
END_RCPP
}
// IndPqd_el_joint
double IndPqd_el_joint(NumericMatrix X);
RcppExport SEXP _PQDtests_IndPqd_el_joint(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type X(XSEXP);
    rcpp_result_gen = Rcpp::wrap(IndPqd_el_joint(X));
    return rcpp_result_gen;
END_RCPP
}
// timesTwo
NumericVector timesTwo(NumericVector x);
RcppExport SEXP _PQDtests_timesTwo(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwo(x));
    return rcpp_result_gen;
END_RCPP
}
// timesTwo2
int timesTwo2(NumericVector x);
RcppExport SEXP _PQDtests_timesTwo2(SEXP xSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type x(xSEXP);
    rcpp_result_gen = Rcpp::wrap(timesTwo2(x));
    return rcpp_result_gen;
END_RCPP
}
// rcpp_hello_world
List rcpp_hello_world();
RcppExport SEXP _PQDtests_rcpp_hello_world() {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    rcpp_result_gen = Rcpp::wrap(rcpp_hello_world());
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_PQDtests_DS", (DL_FUNC) &_PQDtests_DS, 1},
    {"_PQDtests_GofPqd_Dist", (DL_FUNC) &_PQDtests_GofPqd_Dist, 1},
    {"_PQDtests_GofPqd_el_prod", (DL_FUNC) &_PQDtests_GofPqd_el_prod, 1},
    {"_PQDtests_GofPqd_el_joint", (DL_FUNC) &_PQDtests_GofPqd_el_joint, 1},
    {"_PQDtests_IndPqd_Dist", (DL_FUNC) &_PQDtests_IndPqd_Dist, 1},
    {"_PQDtests_IndPqd_el_prod", (DL_FUNC) &_PQDtests_IndPqd_el_prod, 1},
    {"_PQDtests_IndPqd_el_joint", (DL_FUNC) &_PQDtests_IndPqd_el_joint, 1},
    {"_PQDtests_timesTwo", (DL_FUNC) &_PQDtests_timesTwo, 1},
    {"_PQDtests_timesTwo2", (DL_FUNC) &_PQDtests_timesTwo2, 1},
    {"_PQDtests_rcpp_hello_world", (DL_FUNC) &_PQDtests_rcpp_hello_world, 0},
    {NULL, NULL, 0}
};

RcppExport void R_init_PQDtests(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
